sudo: false
dist:  bionic
lang: java
jdk:
  - openjdk8

env:
  global:
    secure: VArEm99oO4wZ34Nnb6hMbB1x1r3r9ou9wL/etYPyDk6ywW6cZQLcyoo40YQxBih4ht7p/P5RQMs0XM2LX5LWSZ7NASjbRhUX0bthc0wGI4lDlFGXYCeq25nuqWj45MbakC3FVMUV1bkcwiGJ/trQIOyqQkdeoTSeXtIK9M3BAp9lAL1biXqBiAIRQzYbtIjD2fV1o9oNqXptpCX4hlYUhC1+g5dejF3Q89X5o9qihGiD0cY3+u9SEWK0O6y/REN14MsBj2I6WLeAuMWvd5J2fxp/BNiMdYLdsvt9pJWpvWdPd75PoDT3ACd+oRk//UaL3d2rKS2vsV4DY0P0bOriGdUacyS+C9/Cz8tLPWvY032e0j3svQ2EyAZJIpX+2on3TxvH+KRO7TvRaoljoHIOs3BjUPLnv59iXnMs54r12jQokbmMCcBvAqV2b5TEJWOuUcotm0NHUne1UCHjyhQOagtQszkRQqTljub+RaXa+f5zWTkelfkhK9ZQM6nmgP8ToKu9T7DCy8oz1EkmG2J/0bm8pW+GKnu6Cp6MjqpDPUIibevqJEvpOpHlutnmvgtXtLzMENz+GK+cSSI/s1Gq1rwSm9JwCMisrIR+50iniLc7DeXUT5vlu6annmo0tOgDfaKb51HMJjoA+n0ljhZB2hbTVeoS1n3Z5djRPRVtfNk=

addons:
  apt:
    packages:
    - python3
    - python3-pip
    - maven
    - gradle

before_install:
  - pip3 install --user --upgrade pip
  - pip3 install --user testresources
  - pip3 install --user --upgrade setuptools
  - pip3 install --user boto3 GitPython github3.py Mako
  - "./git-setup.sh"

install: /bin/true

script:
  - mvn clean verify

before_deploy:
  - rm -rf s3-tools && git clone --depth 1 https://github.com/loonwerks/s3-tools.git
  - export RELEASE_PKG_FILE=$(ls com.collins.trustedsystems.jkindapi.updates/target/com.collins.trustedsystems.jkindapi.updates-*.zip)
  - echo "deploying $RELEASE_PKG_FILE to GitHub releases"
  - xport SNAPSHOT_NUMBER=$(ls repository/target/repository/plugins/com.collins.trustedsystems.jkindapi_*.jar | grep -o "[0-9]\\+\\.[0-9]\\+\\.[0-9]\\+\\.[0-9]\\{12\\}")
  - echo "deploying snapshot number $SNAPSHOT_NUMBER"

deploy:
  # Delete older nightly build releases
  - provider: script
    script: python3 .travis/manage_daily_builds.py
    on:
      branch: master
      condition: $TRAVIS_EVENT_TYPE =~ ^(api|cron)$
  - provider: script
    script: python3 s3-tools/s3tools/DeployToP2CompositeRepository.py --path repository/target/repository --prefix p2/snapshots/jkind-plugin --child-name jkindapi_$SNAPSHOT_NUMBER --logging DEBUG
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: python3 s3-tools/s3tools/ManageSnapshots.py --prefix p2/snapshots/jkind-plugin --logging=DEBUG
    on:
      branch: master
